// packages/example-styled-components/src/App.jsx
/**
 * To showcase the usage of the dnb-ui-lib in React
 *
 */

import React, { useState } from 'react'
import styled from 'styled-components'

import { Button, Input, Icon, Section } from 'dnb-ui-lib/components'
import { H1, H2, P } from 'dnb-ui-lib/elements'
import { bell_medium as Bell } from 'dnb-ui-lib/icons'

export default function App() {
  const [value, setValue] = useState(null)

  const handleClick = e => {
    console.log('handleClick', e)
  }
  const handleValueChange = e => {
    const value = e.value || (e.detail && e.detail.value) || ''
    console.log('handleValueChange', value)
    setValue(value)
  }

  return (
    <div className="dnb-core-style">
      <Section className="dnb-spacing" spacing="true">
        <H1>React Components</H1>
        <P>
          This is not for real world usage. But only to show the
          functionality of the dnb-ui-lib
        </P>
        <Input
          label="Input:"
          placeholder="Type someting ..."
          value={value}
          on_change={handleValueChange}
          right
        />
        <Button
          text="Custom Element with icon"
          icon="chevron_right"
          on_click={handleClick}
        />
      </Section>
      <Section className="dnb-spacing" spacing="true">
        <H2>Colored H2 (by using --color-mint-green)</H2>
        <Title>Colored H2 (by using --color-summer-green)</Title>
        <P>
          Show me an Icon <Icon icon={Bell} size="medium" />
        </P>
      </Section>
    </div>
  )
}

// NB: Will be polyfilled
const Title = styled(H2)`
  .dnb-core-style & {
    color: blue;
    color: var(--color-summer-green);
  }
`

// packages/example-vue/src/App.vue
<template lang="html">
  <div id="app">
    <div
      class="dnb-core-style dnb-spacing dnb-section dnb-section--spacing"
    >
      <h1 class="dnb-h--xx-large">{{ header }}</h1>
      <dnb-button
        text="DNB Button with Icon"
        icon="add"
        icon_position="left"
        @on_click="onClick"
      ></dnb-button>
      <br />
      <dnb-input
        :value="header"
        label="Label:"
        placeholder="My Placeholder"
        @on_change="handleChange"
      ></dnb-input>
    </div>
  </div>
</template>

<script>
import Vue from 'vue'

// import styles for realtime mono repo development
/* import 'dnb-ui-lib/style/components'
import 'dnb-ui-lib/style/themes/open-banking' */

/* import dnb from 'dnb-ui-lib/vue' */
import dnb from 'dnb-ui-lib/vue'

// Bind the components
const components = dnb.getComponents(Vue)

export default {
  name: 'app',
  data: () => ({
    header: 'React Components in Vue'
  }),
  methods: {
    onClick: function(e) {
      console.log('onClick', e)
    },
    handleClick: e => {
      console.log('handleClick', e)
    },
    handleChange: e => {
      const value = e.value || (e.target && e.target.value)
      console.log('handleChange', value)
    }
  },
  components
}
</script>

<style lang="css">
body {
  background-color: var(--color-white);
}
.dnb-section {
  padding-left: 2rem;
}
</style>
